### ISSUE TITLE
Doesn't work with Spring

### ISSUE THREAD

**Issue by st0012** [ruby/debug#208]
```
❯ spring rails c
DEBUGGER: Session start (pid: 37299)
Running via Spring preloader in process 37315
["DEBUGGER Exception: /Users/st0012/projects/debug/lib/debug/thread_client.rb:792",
 #<RuntimeError: DEBUGGER: stop at forked process is not supported yet.>,
 [["/Users/st0012/projects/debug/lib/debug/session.rb:1277:in `check_forked'","DEBUGGER Exception: /Users/st0012/projects/debug/lib/debug/thread_client.rb:792"
,
 "/Users/st0012/projects/debug/lib/debug/thread_client.rb:581:in `wait_next_action'"#<RuntimeError: DEBUGGER: stop at forked process is not supported yet.>,
,
   ["/Users/st0012/projects/debug/lib/debug/thread_client.rb:151:in `on_thread_begin'","/Users/st0012/projects/debug/lib/debug/session.rb:1277:in `check_forked'",

  "/Users/st0012/projects/debug/lib/debug/session.rb:104:in `block in initialize'"  "/Users/st0012/projects/debug/lib/debug/thread_client.rb:581:in `wait_next_action'",
  "/Users/st0012/projects/debug/lib/debug/thread_client.rb:156:in `on_load'"],
  ]
#<Thread:0x00007f82fe33db18 /Users/st0012/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:334 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        3: from /Users/st0012/projects/debug/lib/debug/session.rb:104:in `block in initialize'
        2: from /Users/st0012/projects/debug/lib/debug/thread_client.rb:151:in `on_thread_begin'
        1: from /Users/st0012/projects/debug/lib/debug/thread_client.rb:581:in `wait_next_action'
/Users/st0012/projects/debug/lib/debug/session.rb:1277:in `check_forked': DEBUGGER: stop at forked process is not supported yet. (RuntimeError)
"/Users/st0012/projects/debug/lib/debug/session.rb:87:in `block in initialize'",
  "/Users/st0012/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'",
  "/Users/st0012/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'",
  "/Users/st0012/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'",
  "/Users/st0012/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'",
  "-e:1:in `<main>'"]]
Traceback (most recent call last):
        8: from -e:1:in `<main>'
        7: from /Users/st0012/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        6: from /Users/st0012/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        5: from /Users/st0012/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        4: from /Users/st0012/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        3: from /Users/st0012/projects/debug/lib/debug/session.rb:87:in `block in initialize'
        2: from /Users/st0012/projects/debug/lib/debug/thread_client.rb:156:in `on_load'
        1: from /Users/st0012/projects/debug/lib/debug/thread_client.rb:581:in `wait_next_action'
/Users/st0012/projects/debug/lib/debug/session.rb:1277:in `check_forked': DEBUGGER: stop at forked process is not supported yet. (RuntimeError)
```

**Comment by ko1** [comment]
Now it is intentional.
```
DEBUGGER: stop at forked process is not supported yet. (RuntimeError)
```

**Comment by st0012** [comment]
Yeah I know it's intentionally raised. But `spring` (and perhaps also `zeus`) is still a popular preloading tool with many users (including some of my colleagues). Not being able to use them with the debugger will be a problem to them.

Perhaps this should be supported before the 1.0 release?

**Comment by ko1** [comment]
maybe after 1.0 release.

**Comment by st0012** [comment]
ok 👍

**Comment by st0012** [comment]
I can confirm that this is fixed by https://github.com/ruby/debug/commit/bb5e5c3188c5a76b64cb532812f7f744eb6319f4.
@ko1 thanks for the fix 👍 I think you can make another release for this.

**Comment by ko1** [comment]
oh, great. thank you for confirmation.
