### ISSUE TITLE
The debugger crashes when starting a program using foreman

### ISSUE THREAD

**Issue by dentarg** [ruby/debug#287]
The debugger crashes when you try to debug a program that you started using [foreman](https://github.com/ddollar/foreman). Maybe that scenario is too complicated? I thought I should report it, in case anyone else also runs into this.

Repro:

```shell
$ gem install --no-document foreman debug
Successfully installed foreman-0.87.2
Building native extensions. This could take a while...
Successfully installed debug-1.1.0
2 gems installed

$ cat Procfile
hello: ruby hello.rb

$ cat hello.rb
require "debug"
puts "Hello"
binding.break
puts "World"

$ ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin19]

$ foreman -v
0.87.2

$ foreman start hello
23:27:03 hello.1 | started with pid 47526
23:27:04 hello.1 | Hello
23:27:04 hello.1 | [1, 4] in hello.rb
23:27:04 hello.1 |      1| require "debug"
23:27:04 hello.1 |      2| puts "Hello"
23:27:04 hello.1 | =>   3| binding.break
23:27:04 hello.1 |      4| puts "World"
23:27:04 hello.1 | =>#0 <main> at hello.rb:3
23:27:04 hello.1 | (rdbg) #<Thread:0x00007fd9da874b08@DEBUGGER__::SESSION@server /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:128 run> terminated with exception (report_on_exception is true):
23:27:04 hello.1 | /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline/general_io.rb:38:in `block in getc': uninitialized class variable @@input in Reline::GeneralIO (NameError)
23:27:04 hello.1 | Did you mean?  input=
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline/general_io.rb:37:in `loop'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline/general_io.rb:37:in `getc'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:289:in `block in read_io'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:288:in `loop'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:288:in `read_io'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:246:in `block in inner_readline'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:244:in `loop'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:244:in `inner_readline'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:178:in `readmultiline'
23:27:04 hello.1 |  from /Users/dentarg/.rubies/3.0.2/lib/ruby/3.0.0/forwardable.rb:238:in `readmultiline'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/console.rb:79:in `readline'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/local.rb:74:in `block in readline'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/local.rb:85:in `setup_interrupt'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/local.rb:73:in `readline'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:338:in `wait_command'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:299:in `block in wait_command_loop'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:298:in `loop'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:298:in `wait_command_loop'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:220:in `session_server_main'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:131:in `block in activate'
23:27:04 hello.1 | /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline/general_io.rb:38:in `block in getc': uninitialized class variable @@input in Reline::GeneralIO (NameError)
23:27:04 hello.1 | Did you mean?  input=
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline/general_io.rb:37:in `loop'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline/general_io.rb:37:in `getc'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:289:in `block in read_io'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:288:in `loop'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:288:in `read_io'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:246:in `block in inner_readline'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:244:in `loop'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:244:in `inner_readline'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:178:in `readmultiline'
23:27:04 hello.1 |  from /Users/dentarg/.rubies/3.0.2/lib/ruby/3.0.0/forwardable.rb:238:in `readmultiline'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/console.rb:79:in `readline'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/local.rb:74:in `block in readline'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/local.rb:85:in `setup_interrupt'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/local.rb:73:in `readline'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:338:in `wait_command'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:299:in `block in wait_command_loop'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:298:in `loop'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:298:in `wait_command_loop'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:220:in `session_server_main'
23:27:04 hello.1 |  from /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:131:in `block in activate'
23:27:04 hello.1 | ["DEBUGGER Exception: /Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/thread_client.rb:956",
23:27:04 hello.1 |  #<NameError: uninitialized class variable @@input in Reline::GeneralIO
23:27:04 hello.1 | Did you mean?  input=>,
23:27:04 hello.1 |  ["/Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline/general_io.rb:38:in `block in getc'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline/general_io.rb:37:in `loop'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline/general_io.rb:37:in `getc'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:289:in `block in read_io'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:288:in `loop'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:288:in `read_io'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:246:in `block in inner_readline'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:244:in `loop'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:244:in `inner_readline'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/reline-0.2.7/lib/reline.rb:178:in `readmultiline'",
23:27:04 hello.1 |   "/Users/dentarg/.rubies/3.0.2/lib/ruby/3.0.0/forwardable.rb:238:in `readmultiline'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/console.rb:79:in `readline'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/local.rb:74:in `block in readline'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/local.rb:85:in `setup_interrupt'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/local.rb:73:in `readline'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:338:in `wait_command'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:299:in `block in wait_command_loop'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:298:in `loop'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:298:in `wait_command_loop'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:220:in `session_server_main'",
23:27:04 hello.1 |   "/Users/dentarg/.gem/ruby/3.0.2/gems/debug-1.1.0/lib/debug/session.rb:131:in `block in activate'"]]
23:27:05 hello.1 | exited with code 1
23:27:05 system  | sending SIGTERM to all processes
```

As expected, no problem when not using foreman:

```ruby
$ ruby hello.rb
Hello
[1, 4] in hello.rb
     1| require "debug"
     2| puts "Hello"
=>   3| binding.break
     4| puts "World"
=>#0  <main> at hello.rb:3
Really quit? [Y/n] ^D
```

**Comment by hanazuki** [comment]
This problem seems to be caused because the program running under forman don't have TTY, which is necessary to display interactive debugger UI. This may be fixed in [prerelease versions of reline](https://github.com/ruby/reline/commit/0d98f070830dbdc9d90f0d838ee25f97e93bd7a2) -- but without TTY you cannot enjoy the rich debugging experience such as line editing and completion anyway.

In such a case, you can start a UI-less debugger session by requiring 'debug/open_nonstop' and then attach to it by `rdgb -A`.

**Comment by ko1** [comment]
@dentarg can we close it or do you need discuss more?
