### ISSUE TITLE
Test `test_debugger_takes_log_level_config_from_env_var` is not stable in debug Ruby

### ISSUE THREAD

**Issue by st0012** [ruby/debug#294]
[Example](https://github.com/ruby/debug/runs/3629305104?check_suite_focus=true)

Error:

```
===============================================================================
Failure: test_debugger_takes_log_level_config_from_env_var(DEBUGGER__::LogLevelTest):
  --------------------
  | Debugger Session |
  --------------------
  
  > DEBUGGER (INFO): Session start (pid: 3594)
  > DEBUGGER (INFO): Thread #1 is created.
  > DEBUGGER (INFO): Thread #2 is created.
  > #<Thread:0x00007f8f9518a3b8 /home/runner/work/debug/debug/lib/debug/session.rb:121 run> terminated with exception (report_on_exception is true):
  > /home/runner/work/debug/debug/lib/debug/thread_client.rb:24:in `current': uninitialized constant DEBUGGER__::SESSION (NameError)
  > 
  >         tc = ::DEBUGGER__::SESSION.thread_client
  >                          ^^^^^^^^^
  > Did you mean?  DEBUGGER__::Session
  > 	from /home/runner/work/debug/debug/lib/debug/session.rb:144:in `block in activate'
  > ["DEBUGGER Exception: /home/runner/work/debug/debug/lib/debug/thread_client.rb:955",
  >  #<fatal: No live threads left. Deadlock?
  > 1 threads, 1 sleeps current:0x0000560d6af71050 main thread:0x0000560d6af71050
  > * #<Thread:0x00007f8f987face0 sleep_forever>
  >    rb_thread_t:0x0000560d6af71050 native:0x00007f8f98c45f40 int:0
  >    
  > >,
  >  ["/home/runner/work/debug/debug/lib/debug/thread_client.rb:673:in `pop'",
  >   "/home/runner/work/debug/debug/lib/debug/thread_client.rb:673:in `wait_next_action_'",
  >   "/home/runner/work/debug/debug/lib/debug/thread_client.rb:655:in `wait_next_action'",
  >   "/home/runner/work/debug/debug/lib/debug/thread_client.rb:194:in `wait_reply'",
  >   "/home/runner/work/debug/debug/lib/debug/thread_client.rb:202:in `on_load'",
  >   "/home/runner/work/debug/debug/lib/debug/session.rb:105:in `block in initialize'"]]
  > /home/runner/work/debug/debug/lib/debug/thread_client.rb:673:in `pop': No live threads left. Deadlock? (fatal)
  > 1 threads, 1 sleeps current:0x0000560d6af71050 main thread:0x0000560d6af71050
  > * #<Thread:0x00007f8f987face0 sleep_forever>
  >    rb_thread_t:0x0000560d6af71050 native:0x00007f8f98c45f40 int:0
  >    
  > 	from /home/runner/work/debug/debug/lib/debug/thread_client.rb:673:in `wait_next_action_'
  > 	from /home/runner/work/debug/debug/lib/debug/thread_client.rb:655:in `wait_next_action'
  > 	from /home/runner/work/debug/debug/lib/debug/thread_client.rb:194:in `wait_reply'
  > 	from /home/runner/work/debug/debug/lib/debug/thread_client.rb:202:in `on_load'
  > 	from /home/runner/work/debug/debug/lib/debug/session.rb:105:in `block in initialize'
 
```

From my observation, this error only happens at `debug` Ruby job in 10~20% of the time.

**Comment by ko1** [comment]
test/debug/config_test.rb

**Comment by ko1** [comment]
Maybe (hopefully) it is fixed by recent changes.

**Comment by st0012** [comment]
@ko1 thank you! I'll close this for now then.
