### ISSUE TITLE
Remote debug SIGURG windows support

### ISSUE THREAD

**Issue by sphynx79** [ruby/debug#372]
In windows i try to use debug with Neovim dap, but i think not work because windows not support SIGURG.

I try also:
```
rdbg --open --port 38697 -- prova.rb
DEBUGGER: Debugger can attach via TCP/IP (127.0.0.1:38697)                                                                                                                                        
DEBUGGER: wait for debugger connection...
```

rdbg -A 38697

and receive this error
```
DEBUGGER: ReaderThreadError: unsupported signal `SIGURG'
["C:/Ruby3/lib/ruby/gems/3.0.0/gems/debug-1.3.4/lib/debug/session.rb:2085:in `trap'",
 "C:/Ruby3/lib/ruby/gems/3.0.0/gems/debug-1.3.4/lib/debug/session.rb:2085:in `trap'",
 "C:/Ruby3/lib/ruby/gems/3.0.0/gems/debug-1.3.4/lib/debug/server.rb:214:in `ensure in setup_interrupt'",
 "C:/Ruby3/lib/ruby/gems/3.0.0/gems/debug-1.3.4/lib/debug/server.rb:214:in `setup_interrupt'",
 "C:/Ruby3/lib/ruby/gems/3.0.0/gems/debug-1.3.4/lib/debug/server.rb:67:in `block (2 levels) in activate'",
 "C:/Ruby3/lib/ruby/gems/3.0.0/gems/debug-1.3.4/lib/debug/server.rb:359:in `block (2 levels) in accept'",
 "C:/Ruby3/lib/ruby/3.0.0/socket.rb:810:in `block (2 levels) in accept_loop'",
 "C:/Ruby3/lib/ruby/3.0.0/socket.rb:807:in `each'",
 "C:/Ruby3/lib/ruby/3.0.0/socket.rb:807:in `block in accept_loop'",
 "C:/Ruby3/lib/ruby/3.0.0/socket.rb:805:in `loop'",
 "C:/Ruby3/lib/ruby/3.0.0/socket.rb:805:in `accept_loop'",
 "C:/Ruby3/lib/ruby/gems/3.0.0/gems/debug-1.3.4/lib/debug/server.rb:357:in `block in accept'",
 "C:/Ruby3/lib/ruby/3.0.0/socket.rb:782:in `tcp_server_sockets'",
 "C:/Ruby3/lib/ruby/gems/3.0.0/gems/debug-1.3.4/lib/debug/server.rb:338:in `accept'",
 "C:/Ruby3/lib/ruby/gems/3.0.0/gems/debug-1.3.4/lib/debug/server.rb:48:in `block in activate'"]
DEBUGGER: Disconnected.
```

**Comment by ko1** [comment]
Thank you. It's good point. Hmm... Use SIGINT on Windows... (or all platforms)?

**Comment by sphynx79** [comment]
In this way seems to work fine.

I receive only this message:

DEBUGGER: SIGURG handler is overridden by the debugger

but the debug work fine.

I see in your code that there is one control in file server.rb
```ruby
  def sigurg_overridden? prev_handler
      case prev_handler
      when "SYSTEM_DEFAULT"
        false
      when Proc
        if prev_handler.source_location[0] == __FILE__
          false
        else
          true
        end
      else
        true
      end
    end
```
I try by pry to debug your code and i see that there varialbe prev_handler => "DEFAULT", and your code use "SYSTEM_DEFAULT"

**Comment by ko1** [comment]
Thank you for the information.
I'll revisit it soon.

**Comment by ko1** [comment]
> File.write('/tmp/x', "#{name}\n")

It was completely unused debug print...! Thank you!
