### ISSUE TITLE
`backtrace [n]` should start from the current frame

### ISSUE THREAD

**Issue by st0012** [ruby/debug#496]
(I think this is more like a thing to improve instead of a bug)

When using `backtrace [n]`, it always start from the top frame (index 0), even if the user has moved to another frame (e.g. frame 5). For example, given these frames

```
=>#0    Object#foo(i=0) at target.rb:3
  #1    Object#foo(i=1) at target.rb:5
  #2    Object#foo(i=2) at target.rb:5
  #3    Object#foo(i=3) at target.rb:5
  #4    Object#foo(i=4) at target.rb:5
  #5    Object#foo(i=5) at target.rb:5
  #6    Object#foo(i=6) at target.rb:5
  #7    Object#foo(i=7) at target.rb:5
  #8    Object#foo(i=8) at target.rb:5
  #9    Object#foo(i=9) at target.rb:5
  #10   Object#foo(i=10) at target.rb:5
  #11   Object#foo(i=11) at target.rb:5
  #12   Object#foo(i=12) at target.rb:5
  #13   Object#foo(i=13) at target.rb:5
  #14   Object#foo(i=14) at target.rb:5
  #15   Object#foo(i=15) at target.rb:5
  #16   Object#foo(i=16) at target.rb:5
  #17   Object#foo(i=17) at target.rb:5
  #18   Object#foo(i=18) at target.rb:5
  #19   Object#foo(i=19) at target.rb:5
  #20   Object#foo(i=20) at target.rb:5
```

If we type `bt 10`, it'll list frame `#0` ~ `#9`, which is expected. But if we move to `#9` with `frame 9` and then run `bt 10`, it'll still show `#0` ~ `#9`. 

```
(rdbg) bt 10    # backtrace command
=>#0    Object#foo(i=0) at target.rb:3
  #1    Object#foo(i=1) at target.rb:5
  #2    Object#foo(i=2) at target.rb:5
  #3    Object#foo(i=3) at target.rb:5
  #4    Object#foo(i=4) at target.rb:5
  #5    Object#foo(i=5) at target.rb:5
  #6    Object#foo(i=6) at target.rb:5
  #7    Object#foo(i=7) at target.rb:5
  #8    Object#foo(i=8) at target.rb:5
  #9    Object#foo(i=9) at target.rb:5
  # and 12 frames (use `bt' command for all frames)
(rdbg) f 9    # frame command
=>   5|     foo(i-1)
=>#9    Object#foo(i=9) at target.rb:5
(rdbg) bt 10    # backtrace command
  #0    Object#foo(i=0) at target.rb:3
  #1    Object#foo(i=1) at target.rb:5
  #2    Object#foo(i=2) at target.rb:5
  #3    Object#foo(i=3) at target.rb:5
  #4    Object#foo(i=4) at target.rb:5
  #5    Object#foo(i=5) at target.rb:5
  #6    Object#foo(i=6) at target.rb:5
  #7    Object#foo(i=7) at target.rb:5
  #8    Object#foo(i=8) at target.rb:5
=>#9    Object#foo(i=9) at target.rb:5
  # and 12 frames (use `bt' command for all frames)
(rdbg)
```

IMO, the debugger should show `#9` ~ `#18` instead. Because when we jump to a frame, it's natural to use it as a new starting point for follow up operations. And the current behavior is inconvenient because
- To see next `n` frames, the user needs to compute this: `bt [current frame index + n]`.
- It also means that the first few frames will always be included in the result, which would be annoying when debugging from deeper frames (like `frame 100`).

So I think `backtrace [n]` should take the current frame index into consideration too.

### Example

**Script** 

```rb
def foo(i)
  if i == 0
    binding.b
  else
    foo(i-1)
  end
end

foo(20)
```

**Command**

```
$ rdbg -e "c" target.rb
```

**Comment by ko1** [comment]
Could you survey other debuggers?

**Comment by st0012** [comment]
`byebug` always start from the top frame: https://github.com/deivid-rodriguez/byebug/blob/ddad523427d4ccb5c94aa4858b64b4bbf3d0399c/lib/byebug/commands/where.rb#L57-L59

(Only the unreleased master version accepts argument for `bt` command).

I also tried to observe `gdb`'s `bt` command, but I just couldn't get it work without the error 😞 

```
[New Thread 0x1c0b of process 3387]
[New Thread 0x1e03 of process 3387]
During startup program terminated with signal ?, Unknown signal.
```

But from its description:

> .... starting with the currently executing frame (frame zero), followed by its caller (frame one), and on up the stack.


and the fact that it supports both `n` and `-n` argument, I assume that it starts from the current working frame.

So here's the question: should `bt` with no argument also start from the current frame? I also think that having `-n` argument will be useful here.

Perhaps a more complete `bt` command would look like this?

- `bt` - starting from the current frame and up the stack.
- `bt [n]` - starting from the current frame and up to the next [n-1] frame.
- `bt [-n]` - starting from the current frame and down to the next [n-1] frame or bottom frame.
- `bt full` - starting from the bottom frame and up the stack.
- `bt full [n]` - starting from the bottom frame and up to the [n] frame.

**Comment by ko1** [comment]
on gdb:

```
(gdb) bt
#0  0x00007ffff790c55b in kill () at ../sysdeps/unix/syscall-template.S:78
#1  0x0000555555776e48 in rb_f_kill (argc=<optimized out>, argv=0x7ffff72b4048) at ../../src/trunk/signal.c:481
#2  0x00005555557f4d7b in vm_call_cfunc_with_frame (ec=0x555555982f30, reg_cfp=0x7ffff73b3f90, calling=<optimized out>) at ../../src/trunk/vm_insnhelper.c:3037
#3  0x0000555555809da9 in vm_call_method_each_type (ec=0x555555982f30, cfp=0x7ffff73b3f90, calling=0x7fffffffddf0) at ../../src/trunk/vm_insnhelper.c:3639
#4  0x000055555580a674 in vm_call_method (ec=0x555555982f30, cfp=0x7ffff73b3f90, calling=<optimized out>) at ../../src/trunk/vm_insnhelper.c:3750
#5  0x0000555555802fd2 in vm_sendish (block_handler=<optimized out>, method_explorer=<optimized out>, cd=<optimized out>, reg_cfp=<optimized out>, ec=<optimized out>)
    at ../../src/trunk/vm_callinfo.h:349
#6  vm_exec_core (ec=0x555555982f30, initial=11) at ../../src/trunk/insns.def:778
#7  0x0000555555808ba3 in rb_vm_exec (ec=0x555555982f30, mjit_enable_p=true) at ../../src/trunk/vm.c:2211
#8  0x000055555562297b in rb_ec_exec_node (ec=ec@entry=0x555555982f30, n=n@entry=0x7ffff72af928) at ../../src/trunk/eval.c:280
#9  0x0000555555628f7a in ruby_run_node (n=0x7ffff72af928) at ../../src/trunk/eval.c:321
#10 0x0000555555582f53 in rb_main (argc=<optimized out>, argv=<optimized out>) at ../../src/trunk/main.c:47
#11 0x00007ffff78ed0b3 in __libc_start_main (main=0x555555582de0 <main>, argc=5, argv=0x7fffffffe1d8, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffe1c8) at ../csu/libc-start.c:308
#12 0x0000555555582e1e in _start () at ../../src/trunk/main.c:56
(gdb) f 5
#5  0x0000555555802fd2 in vm_sendish (block_handler=<optimized out>, method_explorer=<optimized out>, cd=<optimized out>, reg_cfp=<optimized out>, ec=<optimized out>)
    at ../../src/trunk/vm_callinfo.h:349
349         return cc->call_;
(gdb) bt 3
#0  0x00007ffff790c55b in kill () at ../sysdeps/unix/syscall-template.S:78
#1  0x0000555555776e48 in rb_f_kill (argc=<optimized out>, argv=0x7ffff72b4048) at ../../src/trunk/signal.c:481
#2  0x00005555557f4d7b in vm_call_cfunc_with_frame (ec=0x555555982f30, reg_cfp=0x7ffff73b3f90, calling=<optimized out>) at ../../src/trunk/vm_insnhelper.c:3037
(More stack frames follow...)
(gdb) bt -3
#10 0x0000555555582f53 in rb_main (argc=<optimized out>, argv=<optimized out>) at ../../src/trunk/main.c:47
#11 0x00007ffff78ed0b3 in __libc_start_main (main=0x555555582de0 <main>, argc=5, argv=0x7fffffffe1d8, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffe1c8) at ../csu/libc-start.c:308
#12 0x0000555555582e1e in _start () at ../../src/trunk/main.c:56
```

on byebug:

```
Stopped by breakpoint 1 at /mnt/c/ko1/src/rb/ruby-debug/target.rb:9

[4, 13] in /mnt/c/ko1/src/rb/ruby-debug/target.rb
    4: end
    5: def bar
    6:   baz
    7: end
    8: def baz
=>  9:   p :baz
   10: end
   11: foo
   12:
   13: __END__
(byebug) bt
--> #0  Object.baz at /mnt/c/ko1/src/rb/ruby-debug/target.rb:9
    #1  Object.bar at /mnt/c/ko1/src/rb/ruby-debug/target.rb:6
    #2  Object.foo at /mnt/c/ko1/src/rb/ruby-debug/target.rb:3
    #3  <top (required)> at /mnt/c/ko1/src/rb/ruby-debug/target.rb:11
(byebug) f 2

[1, 10] in /mnt/c/ko1/src/rb/ruby-debug/target.rb
    1:
    2: def foo
=>  3:   bar
    4: end
    5: def bar
    6:   baz
    7: end
    8: def baz
    9:   p :baz
   10: end
(byebug) bt
    #0  Object.baz at /mnt/c/ko1/src/rb/ruby-debug/target.rb:9
    #1  Object.bar at /mnt/c/ko1/src/rb/ruby-debug/target.rb:6
--> #2  Object.foo at /mnt/c/ko1/src/rb/ruby-debug/target.rb:3
    #3  <top (required)> at /mnt/c/ko1/src/rb/ruby-debug/target.rb:11
(byebug) bt 2
*** NoMethodError Exception: undefined method `bt' for main:Object
```

I'm familiar with gdb's manner.
