### ISSUE TITLE
debug file permission error on windows

### ISSUE THREAD

**Issue by dsisnero** [ruby/debug#506]
**Your environment**

F:\programming\source\repos\ruby\try_ferrum>ruby -v
* ruby:  ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x64-mingw-ucrt]
*  rdbg: 1.4.0

**Describe the bug**
trying to run debug from vscode F5 to Debug current file and gives me an error

F:/windows/tools/ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/config.rb:384:in `check_dir_authority': C:/Users/DOMINI~1/AppData/Local/Temp/ruby-debug-sock-0's mode is 40755 (should be 040700) (RuntimeError)

same with rdbg --open

`rdbg --open amazon1.rb`

F:\programming\source\repos\ruby\try_ferrum>rdbg --open amazon1.rb
F:/windows/tools/ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/config.rb:384:in `check_dir_authority': C:/Users/DOMINI~1/AppData/Local/Temp/ruby-debug-sock-0's mode is 40755 (should be 040700) (RuntimeError)
        from F:/windows/tools/ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/config.rb:401:in `unix_domain_socket_tmpdir'
        from F:/windows/tools/ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/config.rb:421:in `unix_domain_socket_dir'
        from F:/windows/tools/ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/server.rb:406:in `initialize'
        from F:/windows/tools/ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/session.rb:1935:in `new'
        from F:/windows/tools/ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/session.rb:1935:in `open_unix'
        from F:/windows/tools/ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/session.rb:1911:in `open'
        from F:/windows/tools/ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/open.rb:13:in `<top (required)>'
        from <internal:F:/windows/tools/ruby/Ruby31-x64/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:F:/windows/tools/ruby/Ruby31-x64/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'

**To Reproduce**

**Expected behavior**
expected to not have directory permission errors on windows
**Additional context**

**Comment by ko1** [comment]
On windows, UNIX domain socket mode is not available. Could you try tcp/ip mode with port option?

**Comment by arkansas-coder** [comment]
I am using ruby (3.1.0p0) and vscode (1.64.1) on a Windows 10 (10.0.19044) machine. I tried using TCP. Using the terminal command `rdbg --open=vscode --port 12345` reports that the debugger can attach via 127.0.0.1:12345. I tried using `launch.json` with 
```
"type": "rdbg",
"name": "Attach with rdbg",
"request": "attach",
"port": 12345
```
but got the error, 
![ruby-vscode-error](https://user-images.githubusercontent.com/14116217/153090475-1e2e8ac6-356b-4cb5-bce0-26d297c4b228.PNG)
I am unsure if this is an error, or if I don't know what I'm doing. If it's the latter, any help will be appreciated.

**Comment by jabamaus** [comment]
I'm also seeing stuff like:

DEBUGGER: Connected.
DEBUGGER: ReaderThreadError: unsupported signal `SIGURG'
["C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/server_dap.rb:217:in `kill'",
 "C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/server_dap.rb:217:in `process'",
 "C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/server.rb:69:in `block (3 levels) in activate'",
 "C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/server.rb:225:in `setup_interrupt'",
 "C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/server.rb:67:in `block (2 levels) in activate'",
 "C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/server.rb:380:in `block (2 levels) in accept'",
 "C:/Ruby31-x64/lib/ruby/3.1.0/socket.rb:810:in `block (2 levels) in accept_loop'",
 "C:/Ruby31-x64/lib/ruby/3.1.0/socket.rb:807:in `each'",
 "C:/Ruby31-x64/lib/ruby/3.1.0/socket.rb:807:in `block in accept_loop'",
 "C:/Ruby31-x64/lib/ruby/3.1.0/socket.rb:805:in `loop'",
 "C:/Ruby31-x64/lib/ruby/3.1.0/socket.rb:805:in `accept_loop'",
 "C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/server.rb:378:in `block in accept'",
 "C:/Ruby31-x64/lib/ruby/3.1.0/socket.rb:782:in `tcp_server_sockets'",
 "C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/server.rb:364:in `accept'",
 "C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/server.rb:48:in `block in activate'"]
DEBUGGER: Disconnected.

Has anyone got rdbg to work with vscode on windows? I can't get it to work at all.

**Comment by ko1** [comment]
> DEBUGGER: ReaderThreadError: unsupported signal SIGURG' ["C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/debug-1.4.0/lib/debug/server_dap.rb:217:in kill'",

Ah, I see. I'll fix it.
