### ISSUE TITLE
Debuggee sometimes doesn't finish when running tests for DAP.

### ISSUE THREAD

**Issue by ono-max** [ruby/debug#556]
**Your environment**

* `ruby -v`: 
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
* `rdbg -v`:

**Describe the bug**
```terminal
Failure: test_detach_reattach_to_rdbg(DEBUGGER__::DetachTest):
  -------------------------
  | All Protocol Messages |
  -------------------------

  V>D {"seq":2,"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"rdbg","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true},"type":"request"}
  V>D {"seq":3,"command":"attach","arguments":{"type":"rdbg","name":"Attach with rdbg","request":"attach","rdbgPath":"/Users/naotto/workspace/debug/exe/rdbg","debugPort":"/var/folders/kv/w1k6nh1x5fl7vx47b2pd005w0000gn/T/ruby-debug-sock-501/ruby-debug-naotto-8845","autoAttach":true,"__sessionId":"141d9c79-3669-43ec-ac1f-e62598c5a65a"},"type":"request"}
  V>D {"seq":4,"command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"type":"request"}
  V>D {"seq":5,"command":"setExceptionBreakpoints","arguments":{"filters":[],"filterOptions":[{"filterId":"RuntimeError"}]},"type":"request"}
  V>D {"seq":6,"command":"configurationDone","type":"request"}
  V>D {"type":"request","command":"disconnect","arguments":{"restart":false,"terminateDebuggee":false},"seq":7}
  V<D {"type":"response","command":"initialize","request_seq":2,"success":true,"message":"Success","body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":true,"supportsConditionalBreakpoints":true,"supportTerminateDebuggee":true,"supportsTerminateRequest":true,"exceptionBreakpointFilters":[{"filter":"any","label":"rescue any exception"},{"filter":"RuntimeError","label":"rescue RuntimeError","default":true}],"supportsExceptionFilterOptions":true,"supportsStepBack":true,"supportsEvaluateForHovers":true,"supportsCompletionsRequest":true},"seq":1}
  V<D {"type":"event","event":"initialized","seq":2}
  V<D {"type":"response","command":"attach","request_seq":3,"success":true,"message":"Success","seq":3}
  V<D {"type":"response","command":"setFunctionBreakpoints","request_seq":4,"success":true,"message":"Success","seq":4}
  V<D {"type":"response","command":"setExceptionBreakpoints","request_seq":5,"success":true,"message":"Success","body":{"breakpoints":[{"verified":true,"message":"#<DEBUGGER__::CatchBreakpoint:0x00007fbc1280f338 @pat=\"RuntimeError\", @key=[:catch, \"RuntimeError\"], @last_exc=nil, @cond=nil, @command=nil, @path=nil, @deleted=false, @tp=#<TracePoint:enabled>>"}]},"seq":5}
  V<D {"type":"response","command":"configurationDone","request_seq":6,"success":true,"message":"Success","seq":6}
  V<D {"type":"event","event":"stopped","body":{"reason":"pause","threadId":1,"allThreadsStopped":true},"seq":7}
  V<D {"type":"response","command":"disconnect","request_seq":7,"success":true,"message":"Success","seq":8}
  V>D {"seq":2,"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"rdbg","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true},"type":"request"}
  V>D {"seq":3,"command":"attach","arguments":{"type":"rdbg","name":"Attach with rdbg","request":"attach","rdbgPath":"/Users/naotto/workspace/debug/exe/rdbg","debugPort":"/var/folders/kv/w1k6nh1x5fl7vx47b2pd005w0000gn/T/ruby-debug-sock-501/ruby-debug-naotto-8845","autoAttach":true,"__sessionId":"141d9c79-3669-43ec-ac1f-e62598c5a65a"},"type":"request"}
  V>D {"seq":4,"command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"type":"request"}
  V>D {"seq":5,"command":"setExceptionBreakpoints","arguments":{"filters":[],"filterOptions":[{"filterId":"RuntimeError"}]},"type":"request"}
  V>D {"seq":6,"command":"configurationDone","type":"request"}
  V<D {"type":"response","command":"initialize","request_seq":2,"success":true,"message":"Success","body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":true,"supportsConditionalBreakpoints":true,"supportTerminateDebuggee":true,"supportsTerminateRequest":true,"exceptionBreakpointFilters":[{"filter":"any","label":"rescue any exception"},{"filter":"RuntimeError","label":"rescue RuntimeError","default":true}],"supportsExceptionFilterOptions":true,"supportsStepBack":true,"supportsEvaluateForHovers":true,"supportsCompletionsRequest":true},"seq":1}
  V<D {"type":"event","event":"initialized","seq":2}
  V<D {"type":"response","command":"attach","request_seq":3,"success":true,"message":"Success","seq":3}
  V<D {"type":"response","command":"setFunctionBreakpoints","request_seq":4,"success":true,"message":"Success","seq":4}
  V<D {"type":"response","command":"setExceptionBreakpoints","request_seq":5,"success":true,"message":"Success","body":{"breakpoints":[{"verified":true,"message":"true"}]},"seq":5}
  V<D {"type":"response","command":"configurationDone","request_seq":6,"success":true,"message":"Success","seq":6}
  V>D {"type":"request","command":"disconnect","arguments":{"restart":true,"terminateDebuggee":true},"seq":7}
  V<D {"type":"event","event":"stopped","body":{"reason":"pause","threadId":1,"allThreadsStopped":true},"seq":7}
  V<D {"type":"response","command":"disconnect","request_seq":7,"success":true,"message":"Success","seq":8}

  --------------------------
  | Last Protocol Messages |
  --------------------------

  {
    "type": "request",
    "command": "disconnect",
    "arguments": {
      "restart": true,
      "terminateDebuggee": true
    },
    "seq": 7
  }
  {
    "type": "event",
    "event": "stopped",
    "body": {
      "reason": "pause",
      "threadId": 1,
      "allThreadsStopped": true
    },
    "seq": 7
  }
  {
    "type": "response",
    "command": "disconnect",
    "request_seq": 7,
    "success": true,
    "message": "Success",
    "seq": 8
  }

  --------------------
  | Debuggee Session |
  --------------------

  > EBUGGER: Debugger can attach via UNIX domain socket (/var/folders/kv/w1k6nh1x5fl7vx47b2pd005w0000gn/T/ruby-debug-sock-501/ruby-debug-naotto-73888-10)
  > DEBUGGER: Connected.
  > DEBUGGER: Disconnected.
  > DEBUGGER: Connected.
  > DEBUGGER: Disconnected.


  -------------------
  | Failure Message |
  -------------------

  Expected the debuggee program to finish.
/Users/naotto/workspace/debug/test/support/assertions.rb:97:in `assert_block'
/Users/naotto/workspace/debug/test/support/protocol_utils.rb:249:in `execute_dap_scenario'
/Users/naotto/workspace/debug/test/support/protocol_utils.rb:46:in `run_protocol_scenario'
/Users/naotto/workspace/debug/test/protocol/detach_test.rb:23:in `test_detach_reattach_to_rdbg'
     20:     RUBY
     21:
     22:     def test_detach_reattach_to_rdbg
  => 23:       run_protocol_scenario PROGRAM do
     24:         assert_reattach
     25:         req_terminate_debuggee
     26:       end
```
**To Reproduce**
Run tests several times.

**Expected behavior**
Tests should be passed.

**Additional context**

**Comment by ono-max** [comment]
I may fix this issue. I'll reopen this one if I find this issue again.
