### ISSUE TITLE
Debugger fails tests because of `uninitialized constant DEBUGGER__::ThreadClient::SESSION`

### ISSUE THREAD

**Issue by ono-max** [ruby/debug#560]
**Your environment**

* `ruby -v`: 

* `rdbg -v`:

**Describe the bug**
```
Failure: test_finish_leaves_from_the_method(DEBUGGER__::FinishTest):
  -------------------------
  | All Protocol Messages |
  -------------------------

  V>D {"seq":2,"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"rdbg","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true},"type":"request"}
  V>D {"seq":3,"command":"attach","arguments":{"type":"rdbg","name":"Attach with rdbg","request":"attach","rdbgPath":"/Users/s15236/workspace/debug/exe/rdbg","debugPort":"/var/folders/kv/w1k6nh1x5fl7vx47b2pd005w0000gn/T/ruby-debug-sock-501/ruby-debug-naotto-8845","autoAttach":true,"__sessionId":"141d9c79-3669-43ec-ac1f-e62598c5a65a"},"type":"request"}
  V>D {"seq":4,"command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"type":"request"}
  V>D {"seq":5,"command":"setExceptionBreakpoints","arguments":{"filters":[],"filterOptions":[{"filterId":"RuntimeError"}]},"type":"request"}
  V>D {"seq":6,"command":"configurationDone","type":"request"}
  V>D {"type":"request","command":"setBreakpoints","arguments":{"source":{"name":"/var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220313-45691-xapf0p.rb","path":"/var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220313-45691-xapf0p.rb","sourceReference":null},"breakpoints":[{"line":3,"condition":null}]},"seq":7}

  --------------------------
  | Last Protocol Messages |
  --------------------------

  {
    "seq": 5,
    "command": "setExceptionBreakpoints",
    "arguments": {
      "filters": [

      ],
      "filterOptions": [
        {
          "filterId": "RuntimeError"
        }
      ]
    },
    "type": "request"
  }
  {
    "seq": 6,
    "command": "configurationDone",
    "type": "request"
  }
  {
    "type": "request",
    "command": "setBreakpoints",
    "arguments": {
      "source": {
        "name": "/var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220313-45691-xapf0p.rb",
        "path": "/var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220313-45691-xapf0p.rb",
        "sourceReference": null
      },
      "breakpoints": [
        {
          "line": 3,
          "condition": null
        }
      ]
    },
    "seq": 7
  }

  --------------------
  | Debuggee Session |
  --------------------

  > EBUGGER: Debugger can attach via UNIX domain socket (/var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/ruby-debug-sock-746464807/ruby-debug-s15236-45691-14)
  > DEBUGGER: Connected.
  > DEBUGGER: ReaderThreadError: uninitialized constant DEBUGGER__::ThreadClient::SESSION
  >
  >         thc = SESSION.get_thread_client
  >               ^^^^^^^
  > Did you mean?  DEBUGGER__::Session
  > ["/Users/s15236/workspace/debug/lib/debug/thread_client.rb:29:in `current'",
  >  "/Users/s15236/workspace/debug/lib/debug/session.rb:119:in `block in initialize'",
  >  "/Users/s15236/workspace/debug/lib/debug/server.rb:112:in `require_relative'",
  >  "/Users/s15236/workspace/debug/lib/debug/server.rb:112:in `greeting'",
  >  "/Users/s15236/workspace/debug/lib/debug/server.rb:53:in `block (3 levels) in activate'",
  >  "/Users/s15236/workspace/debug/lib/debug/server.rb:51:in `synchronize'",
  >  "/Users/s15236/workspace/debug/lib/debug/server.rb:51:in `block (2 levels) in activate'",
  >  "/Users/s15236/workspace/debug/lib/debug/server.rb:436:in `block in accept'",
  >  "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:810:in `block (2 levels) in accept_loop'",
  >  "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:807:in `each'",
  >  "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:807:in `block in accept_loop'",
  >  "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:805:in `loop'",
  >  "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:805:in `accept_loop'",
  >  "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1165:in `block in unix_server_loop'",
  >  "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1119:in `unix_server_socket'",
  >  "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1164:in `unix_server_loop'",
  >  "/Users/s15236/workspace/debug/lib/debug/server.rb:432:in `accept'",
  >  "/Users/s15236/workspace/debug/lib/debug/server.rb:48:in `block in activate'"]
  > DEBUGGER: Disconnected.
  > #<Thread:0x0000000102638640@DEBUGGER__::Server::reader /Users/s15236/workspace/debug/lib/debug/server.rb:43 run> terminated with exception (report_on_exception is true):
  > /Users/s15236/workspace/debug/lib/debug/server.rb:89:in `cleanup_reader': undefined method `close' for nil:NilClass (NoMethodError)
  >
  >       @q_msg.close
  >             ^^^^^^
  > 	from /Users/s15236/workspace/debug/lib/debug/server.rb:78:in `block (2 levels) in activate'
  > 	from /Users/s15236/workspace/debug/lib/debug/server.rb:436:in `block in accept'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:810:in `block (2 levels) in accept_loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:807:in `each'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:807:in `block in accept_loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:805:in `loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:805:in `accept_loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1165:in `block in unix_server_loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1119:in `unix_server_socket'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1164:in `unix_server_loop'
  > 	from /Users/s15236/workspace/debug/lib/debug/server.rb:432:in `accept'
  > 	from /Users/s15236/workspace/debug/lib/debug/server.rb:48:in `block in activate'
  > ["DEBUGGER Exception: /Users/s15236/workspace/debug/lib/debug/thread_client.rb:1025",
  >  #<NoMethodError: undefined method `close' for nil:NilClass
  >
  >       @q_msg.close
  >             ^^^^^^>,
  >  ["/Users/s15236/workspace/debug/lib/debug/server.rb:89:in `cleanup_reader'",
  >   "/Users/s15236/workspace/debug/lib/debug/server.rb:78:in `block (2 levels) in activate'",
  >   "/Users/s15236/workspace/debug/lib/debug/server.rb:436:in `block in accept'",
  >   "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:810:in `block (2 levels) in accept_loop'",
  >   "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:807:in `each'",
  >   "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:807:in `block in accept_loop'",
  >   "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:805:in `loop'",
  >   "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:805:in `accept_loop'",
  >   "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1165:in `block in unix_server_loop'",
  >   "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1119:in `unix_server_socket'",
  >   "/Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1164:in `unix_server_loop'",
  >   "/Users/s15236/workspace/debug/lib/debug/server.rb:432:in `accept'",
  >   "/Users/s15236/workspace/debug/lib/debug/server.rb:48:in `block in activate'"]]
  > #<Thread:0x0000000102638488@DEBUGGER__::SESSION@server /Users/s15236/workspace/debug/lib/debug/session.rb:149 aborting> terminated with exception (report_on_exception is true):
  > /Users/s15236/workspace/debug/lib/debug/server.rb:89:in `cleanup_reader': undefined method `close' for nil:NilClass (NoMethodError)
  >
  >       @q_msg.close
  >             ^^^^^^
  > 	from /Users/s15236/workspace/debug/lib/debug/server.rb:78:in `block (2 levels) in activate'
  > 	from /Users/s15236/workspace/debug/lib/debug/server.rb:436:in `block in accept'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:810:in `block (2 levels) in accept_loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:807:in `each'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:807:in `block in accept_loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:805:in `loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:805:in `accept_loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1165:in `block in unix_server_loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1119:in `unix_server_socket'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1164:in `unix_server_loop'
  > 	from /Users/s15236/workspace/debug/lib/debug/server.rb:432:in `accept'
  > 	from /Users/s15236/workspace/debug/lib/debug/server.rb:48:in `block in activate'
  > /Users/s15236/workspace/debug/lib/debug/server.rb:89:in `cleanup_reader': undefined method `close' for nil:NilClass (NoMethodError)
  >
  >       @q_msg.close
  >             ^^^^^^
  > 	from /Users/s15236/workspace/debug/lib/debug/server.rb:78:in `block (2 levels) in activate'
  > 	from /Users/s15236/workspace/debug/lib/debug/server.rb:436:in `block in accept'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:810:in `block (2 levels) in accept_loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:807:in `each'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:807:in `block in accept_loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:805:in `loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:805:in `accept_loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1165:in `block in unix_server_loop'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1119:in `unix_server_socket'
  > 	from /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/3.1.0/socket.rb:1164:in `unix_server_loop'
  > 	from /Users/s15236/workspace/debug/lib/debug/server.rb:432:in `accept'
  > 	from /Users/s15236/workspace/debug/lib/debug/server.rb:48:in `block in activate'


  -------------------
  | Failure Message |
  -------------------

  TIMEOUT ERROR (10 sec) while waiting: request_seq 7.
/Users/s15236/workspace/debug/test/support/assertions.rb:97:in `assert_block'
/Users/s15236/workspace/debug/test/support/protocol_utils.rb:527:in `rescue in find_response'
/Users/s15236/workspace/debug/test/support/protocol_utils.rb:515:in `find_response'
/Users/s15236/workspace/debug/test/support/protocol_utils.rb:508:in `find_crt_dap_response'
/Users/s15236/workspace/debug/test/support/protocol_utils.rb:311:in `block in req_set_breakpoints_on_dap'
/Users/s15236/workspace/debug/test/support/protocol_utils.rb:298:in `each'
/Users/s15236/workspace/debug/test/support/protocol_utils.rb:298:in `req_set_breakpoints_on_dap'
/Users/s15236/workspace/debug/test/support/protocol_utils.rb:56:in `req_add_breakpoint'
/Users/s15236/workspace/debug/test/protocol/finish_test.rb:21:in `block in test_finish_leaves_from_the_method'
     18:
     19:     def test_finish_leaves_from_the_method
     20:       run_protocol_scenario PROGRAM do
  => 21:         req_add_breakpoint 3
     22:         req_continue
     23:         assert_line_num 4
     24:         req_finish
/Users/s15236/workspace/debug/test/support/protocol_utils.rb:245:in `execute_dap_scenario'
/Users/s15236/workspace/debug/test/support/protocol_utils.rb:46:in `run_protocol_scenario'
/Users/s15236/workspace/debug/test/protocol/finish_test.rb:20:in `test_finish_leaves_from_the_method'
```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by ko1** [comment]
ec0a557942e6fd1e1daadc8042352670be1a61fb may solve it.
