### ISSUE TITLE
Debug console raises exception and exits on typos

### ISSUE THREAD

**Issue by kmewhort** [ruby/debug#571]
**Your environment**

* `ruby -v`: `ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]`
* `rdbg -v`: `rdbg 1.4.0`

**Describe the bug**
When using `binding.break` to set a break point and poking around at the break, any typo or syntax error will cause an uncaught exception that bubbles right up and exits the console.

I'm not sure if this is intended behaviour, but it's definitely a pain when doing exploratory work at the break point.

**To Reproduce**
1. Set a breakpoint with `binding.break`
2. Run code to the breakpoint
3. Type `putz "I have asyntax error"`

**Expected behavior**
My expectation would be that the exception is shown to the console, but I remain at the breakpoint.

**Additional context**

**Comment by haacs** [comment]
is fixed in https://github.com/ruby/debug/pull/498, just not released in a new version yet.

To get the fix from master I changed the following in my gemfile:
```patch
- gem 'debug'
+ git_source(:github) { |repo| "https://github.com/#{repo}.git" }
+ gem 'debug', github: 'ruby/debug'
```
and ran `bundle pristine`

**Comment by kmewhort** [comment]
Oh nice!  Thanks.

**Comment by runephilosof-karnovgroup** [comment]
This has not been fixed. https://github.com/ruby/debug/pull/498 seems to be about fixing autocompletion. This bug is not about autocompletion.
```
(ruby) putz "I have asyntax error"
["DEBUGGER Exception: /usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:1233",
 #<LocalJumpError: break from proc-closure>,
 ["/usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:457:in `block in frame_eval'",
  "/usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:456:in `each'",
  "/usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:456:in `rescue in frame_eval'",
  "/usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:435:in `frame_eval'",
  "/usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:1033:in `wait_next_action_'",
  "/usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:856:in `wait_next_action'",
  "/usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:320:in `suspend'",
  "/usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:251:in `on_breakpoint'",
  "/usr/local/bundle/gems/debug-1.7.1/lib/debug/breakpoint.rb:69:in `suspend'",
  "/usr/local/bundle/gems/debug-1.7.1/lib/debug/breakpoint.rb:178:in `block in setup'",
  "/usr/local/bundle/gems/debug-1.7.1/lib/debug/session.rb:2586:in `debugger'",
...
F

Failures:

  1) RefreshBaseSectionReferenceWorker updates BaseSectionReferences
     Failure/Error: debugger
     
     LocalJumpError:
       break from proc-closure
     # /usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:457:in `block in frame_eval'
     # /usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:456:in `each'
     # /usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:456:in `rescue in frame_eval'
     # /usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:435:in `frame_eval'
     # /usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:1033:in `wait_next_action_'
     # /usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:856:in `wait_next_action'
     # /usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:320:in `suspend'
     # /usr/local/bundle/gems/debug-1.7.1/lib/debug/thread_client.rb:251:in `on_breakpoint'
     # /usr/local/bundle/gems/debug-1.7.1/lib/debug/breakpoint.rb:69:in `suspend'
     # /usr/local/bundle/gems/debug-1.7.1/lib/debug/breakpoint.rb:178:in `block in setup'
     # /usr/local/bundle/gems/debug-1.7.1/lib/debug/session.rb:2586:in `debugger'
     # ./app/utils/find_latest_pro_document_by_id.rb:18:in `call'
     # ./app/utils/find_latest_pro_document_by_id.rb:8:in `call'
     # ./app/services/refresh_base_section_reference_service.rb:23:in `block in find_pro_document'
     # ./app/utils/pro_document_cache_key.rb:5:in `call'
     # ./app/services/refresh_base_section_reference_service.rb:22:in `find_pro_document'
     # ./app/services/refresh_base_section_reference_service.rb:6:in `block in call'
     # ./app/services/refresh_base_section_reference_service.rb:5:in `call'
     # ./app/workers/refresh_base_section_reference_worker.rb:9:in `perform'
     # ./spec/workers/refresh_base_section_reference_worker_spec.rb:17:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/vcr-6.1.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /usr/local/bundle/gems/vcr-6.1.0/lib/vcr.rb:194:in `use_cassette'
     # ./spec/workers/refresh_base_section_reference_worker_spec.rb:16:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `putz' for ...
```
