### ISSUE TITLE
`test_break_only_stops_when_path_matches` failed

### ISSUE THREAD

**Issue by ono-max** [ruby/debug#591]
**Your environment**

* `ruby -v`: 
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]
* `rdbg -v`:

**Describe the bug**
```shell
$ ruby test/debug/break_test.rb
Tests on local and remote. You can disable remote tests with RUBY_DEBUG_TEST_NO_REMOTE=1.
Loaded suite test/debug/break_test
Started
...............F
================================================================================================================================================================================================================================================================================
Failure: test_break_only_stops_when_path_matches(DEBUGGER__::BreakAtInstanceMethodsTest::PathOptionTest):
  #<Test::Unit::AssertionFailedError:
  --------------------
  | Debugger Session |
  --------------------

  > [1, 7] in /var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220328-77077-q24op2.rb
  > =>   1| class Foo
  >      2|   def bar; end
  >      3| end
  >      4|
  >      5| Foo.new.bar
  >      6|
  >      7| load "/var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/503f6b1dbafoopy20220328-77077-34msvr.rb"
  > =>#0	<main> at /var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220328-77077-q24op2.rb:1
  > break Foo#bar path: /.py/
  > (rdbg) break Foo#bar path: /.py/
uninitialized constant Foo
  >
  > Foo
  > ^^^
  > #0  BP - Method (pending)  Foo#bar
  > (rdbg) c
DEBUGGER:  BP - Method  Foo#bar at /var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220328-77077-q24op2.rb:2 is activated.
  > [1, 7] in /var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220328-77077-q24op2.rb
  >      1| class Foo
  > =>   2|   def bar; end
  >      3| end
  >      4|
  >      5| Foo.new.bar
  >      6|
  >      7| load "/var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/503f6b1dbafoopy20220328-77077-34msvr.rb"
  > =>#0	Foo#bar at /var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220328-77077-q24op2.rb:2
  >   #1	<main> at /var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220328-77077-q24op2.rb:5
  >
  > Stop by #0  BP - Method  Foo#bar at /var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220328-77077-q24op2.rb:2
  > (rdbg) c
[1, 7] in /var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220328-77077-q24op2.rb
  >      1| class Foo
  > =>   2|   def bar; end
  >      3| end
  >      4|
  >      5| Foo.new.bar
  >      6|
  >      7| load "/var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/503f6b1dbafoopy20220328-77077-34msvr.rb"
  > =>#0	Foo#bar at /var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220328-77077-q24op2.rb:2
  >   #1	<top (required)> at /var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/503f6b1dbafoopy20220328-77077-34msvr.rb:1
  >   # and 2 frames (use `bt' command for all frames)
  >
  > Stop by #0  BP - Method  Foo#bar at /var/folders/5j/z2c9zm7124q81f_py4xmd3scp7w9j7/T/debug-20220328-77077-q24op2.rb:2




  -------------------
  | Failure Message |
  -------------------

  Expected the REPL prompt to finish on LOCAL mode.>.
/Users/s15236/workspace/debug/test/support/assertions.rb:97:in `assert_block'
/Users/s15236/workspace/debug/test/support/utils.rb:78:in `rescue in block in debug_code'
/Users/s15236/workspace/debug/test/support/utils.rb:63:in `block in debug_code'
/Users/s15236/workspace/debug/test/support/utils.rb:171:in `prepare_test_environment'
/Users/s15236/workspace/debug/test/support/utils.rb:61:in `debug_code'
test/debug/break_test.rb:244:in `block in test_break_only_stops_when_path_matches'
     241:           end
     242:
     243:           # special characters should be treated differently in Regexp/String form
  => 244:           debug_code(program(extra_file.path)) do
     245:             type "break Foo#bar path: /.py/"
     246:             type 'c'
     247:             assert_line_text(/#{extra_file.path}/)
/Users/s15236/workspace/debug/test/support/test_case.rb:51:in `with_extra_tempfile'
test/debug/break_test.rb:227:in `test_break_only_stops_when_path_matches'
================================================================================================================================================================================================================================================================================
.......................
Finished in 19.650532 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
39 tests, 44 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.4359% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1.98 tests/s, 2.24 assertions/s
```

**To Reproduce**

**Expected behavior**

**Additional context**
The test doesn't fail in CI.

**Comment by st0012** [comment]
Actually, it doesn't fail on my macOS:

```
❯  ruby test/debug/break_test.rb
Tests on local and remote. You can disable remote tests with RUBY_DEBUG_TEST_NO_REMOTE=1.
Loaded suite test/debug/break_test
Started
.......................................
Finished in 20.616344 seconds.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
39 tests, 44 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1.89 tests/s, 2.13 assertions/s
```

I'll give the output a look later today.

**Comment by ono-max** [comment]
Oh, I see.

**Comment by st0012** [comment]
It's caused by an accidental name matching against the temp folder's name. I've added #592 to reduce the chance for that to happen.
