### ISSUE TITLE
Remote Debuggee crashes on Debugger's "quit" command

### ISSUE THREAD

**Issue by jpau-besmartee** [ruby/debug#622]
**Your environment**
Windows 11: Using Docker Desktop container (with docker compose) running Alpine, using foreman to run Procfile on start

* `ruby -v`: `ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]`
* `rdbg -v`: `rdbg 1.5.0`

**Describe the bug**
Running `quit` command on attached debugger causes the debuggee to exit (logs provided below).

**To Reproduce**
1. Set up a rails application on a docker container (I can provide my configurations if needed).
2. Add a `require 'debug/open_nonstop'` in the `bin/rails` file at the top of the file.
3. Add a line in Procfile to start `bin/rails server -p 3000 -b 0.0.0.0` if it's not already there
4. Set up your docker-compose.yml to run the `bin/dev` command on start to run foreman using the Procfile
5. Start docker container `docker compose up -d`
6. Attach to debuggee using `docker compose exec <container name> rdbg --attach`
7. Add `debugger` line in the application and trigger the breakpoint (by visiting a web page or any method you prefer)
8. In rdbg console you attached to (in step 6) type `quit`
9. Debugging process quits but the container also breaks saying:
-- ```unsupported:  \  exited with code 1```

**Expected behavior**
Debugger should gracefully detach and debuggee should be open to accept a new debugger attachment.

**Additional context**
Dockerfile uses `FROM ruby:3.1.1-alpine3.15` base image.

Whole docker container terminal output when following above steps to reproduce:
```
20:26:35 web.1  | started with pid 10
20:26:35 web.1  | DEBUGGER: Debugger can attach via UNIX domain socket (/tmp/ruby-debug-sock-0/ruby-debug-ruby-debug-10)
20:26:37 web.1  | DEBUGGER: Connected.
20:26:43 web.1  | => Booting Puma
20:26:43 web.1  | => Rails 7.0.2.3 application starting in development 
20:26:43 web.1  | => Run `bin/rails server --help` for more startup options
20:26:44 web.1  | Puma starting in single mode...
20:26:44 web.1  | * Puma version: 5.6.4 (ruby 3.1.1-p18) ("Birdie's Version")
20:26:44 web.1  | *  Min threads: 5
20:26:44 web.1  | *  Max threads: 5
20:26:44 web.1  | *  Environment: development
20:26:44 web.1  | *          PID: 10
20:26:44 web.1  | * Listening on http://0.0.0.0:3000
20:26:44 web.1  | Use Ctrl-C to stop
20:26:47 web.1  | Started GET "/" for 192.168.32.1 at 2022-04-13 20:26:47 +0000
20:26:47 web.1  | Cannot render console from 192.168.32.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
20:26:47 web.1  |   ActiveRecord::SchemaMigration Pluck (1.0ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
20:26:47 web.1  | Processing by ApplicationController#index as HTML
20:26:50 web.1  | unsupported: 
20:26:51 web.1  | exited with code 1
20:26:51 system | sending SIGTERM to all processes
```

**Comment by ko1** [comment]
Thank you. Does it work on multi-process mode?
(Can I see debug REPL console log?)

**Comment by jpau-besmartee** [comment]
> Thank you. Does it work on multi-process mode? (Can I see debug REPL console log?)

Here's the REPL console log including the command I used to attach to the remote debugger:

```bash
docker compose exec app rdbg --attach ruby-debug-ruby-debug-10
# No sourcefile available for /usr/local/bundle/gems/puma-5.6.4/lib/puma/single.rb
=>#0    [C] Thread#join at /usr/local/bundle/gems/puma-5.6.4/lib/puma/single.rb:61
  #1    Puma::Single#run at /usr/local/bundle/gems/puma-5.6.4/lib/puma/single.rb:61
  # and 16 frames (use `bt' command for all frames)

Stop by SIGURG
(rdbg:remote) continue    # command
[1, 10] in /app/app/controllers/fees_controller.rb
     1| class FeesController < ApplicationController
     2|   before_action :set_fee, only: %i[ show edit update destroy ]
     3|
     4|   # GET /fees or /fees.json
     5|   def index
=>   6|     debugger
     7|     @fees = Fee.all
     8|   end
     9|
    10|   # GET /fees/1 or /fees/1.json
=>#0    FeesController#index at /app/app/controllers/fees_controller.rb:6
  #1    ActionController::BasicImplicitRender#send_action(method="index", args=[]) at /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_controller/metal/basic_implicit_render.rb:6
  # and 73 frames (use `bt' command for all frames)
(rdbg:remote) quit    # command
Really quit? [Y/n] Y
disconnected (quit)
```
After that `quit` command is where the docker container exits.

When you say "multi-process mode" are you referring to `rdbg --open`? If so, here's the docker terminal output when I remove the `require 'debug/open_nonstop'` and add this to my Procfile `rdbg --open -c -- bin/rails server -p 3000 -b 0.0.0.0`:

```
15:35:25 web.1  | started with pid 9
15:35:25 web.1  | DEBUGGER: Debugger can attach via UNIX domain socket (/tmp/ruby-debug-sock-0/ruby-debug-ruby-debug-9)
15:35:25 web.1  | DEBUGGER: wait for debugger connection...
15:36:06 web.1  | DEBUGGER: Connected.
15:36:20 web.1  | => Booting Puma
15:36:20 web.1  | => Rails 7.0.2.3 application starting in development 
15:36:20 web.1  | => Run `bin/rails server --help` for more startup options
15:36:21 web.1  | Puma starting in single mode...
15:36:21 web.1  | * Puma version: 5.6.4 (ruby 3.1.2-p20) ("Birdie's Version")
15:36:21 web.1  | *  Min threads: 5
15:36:21 web.1  | *  Max threads: 5
15:36:21 web.1  | *  Environment: development
15:36:21 web.1  | *          PID: 9
15:36:21 web.1  | * Listening on http://0.0.0.0:3000
15:36:21 web.1  | Use Ctrl-C to stop
15:36:22 web.1  | Started GET "/fees" for 192.168.32.1 at 2022-04-18 15:36:22 +0000
15:36:22 web.1  | Cannot render console from 192.168.32.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
15:36:22 web.1  |   ActiveRecord::SchemaMigration Pluck (1.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
15:36:22 web.1  | Processing by FeesController#index as HTML
15:36:34 web.1  | unsupported: 
15:36:34 web.1  | exited with code 1
```

And the corresponding REPL console:

```bash
docker compose exec app rdbg --attach
[1, 4] in bin/rails
     1| #!
=>   2| APP_PATH = File.expand_path("../config/application", __dir__)
     3| require_relative "../config/boot"
     4| require "rails/commands"
=>#0    <main> at bin/rails:2
(rdbg:remote) continue    # command
[1, 10] in /app/app/controllers/fees_controller.rb
     1| class FeesController < ApplicationController
     2|   before_action :set_fee, only: %i[ show edit update destroy ]
     3|
     4|   # GET /fees or /fees.json
     5|   def index
=>   6|     debugger
     7|     @fees = Fee.all
     8|   end
     9|
    10|   # GET /fees/1 or /fees/1.json
=>#0    FeesController#index at /app/app/controllers/fees_controller.rb:6
  #1    ActionController::BasicImplicitRender#send_action(method="index", args=[]) at /usr/local/bundle/gems/actionpack-7.0.2.3/lib/action_controller/metal/basic_implicit_render.rb:6
  # and 73 frames (use `bt' command for all frames)
(rdbg:remote) quit    # command
Really quit? [Y/n] Y
disconnected (quit)
```

As you can see I forgot to run this in `nonstop` mode so it stopped on the `rails` command which I continued. Let me know if there is anything you need.

**Comment by BobbyMcWho** [comment]
I can confirm this is happening for me as well:
```
(rdbg:remote) quit    # command
Really quit? [Y/n] disconnected (No such file or directory @ rb_sysopen - 0.0.0.0)
```
```
web-debug_1              | DEBUGGER: wait for debugger connection...
web-debug_1              | DEBUGGER: Connected.
web-debug_1              | unsupported: 
```

**Comment by BobbyMcWho** [comment]
Bugsnag caught this the last time I quit via vscode, not certain if it's relevant 
```
web_1                    | DEBUGGER: Disconnected.
web_1                    | #<Thread:0x0000aaaadecb2c60@DEBUGGER__::SESSION@server@/usr/local/bundle/gems/debug-1.5.0/lib/debug/session.rb:144 run> terminated with exception (report_on_exception is true):
web_1                    | /usr/local/bundle/gems/debug-1.5.0/lib/debug/server_dap.rb:158:in `send': undefined method `write' for nil:NilClass (NoMethodError)
web_1                    |      from /usr/local/bundle/gems/debug-1.5.0/lib/debug/server_dap.rb:183:in `send_event'
web_1                    |      from /usr/local/bundle/gems/debug-1.5.0/lib/debug/server_dap.rb:392:in `event'
web_1                    |      from /usr/local/bundle/gems/debug-1.5.0/lib/debug/session.rb:238:in `process_event'
web_1                    |      from /usr/local/bundle/gems/debug-1.5.0/lib/debug/session.rb:194:in `session_server_main'
web_1                    |      from /usr/local/bundle/gems/debug-1.5.0/lib/debug/session.rb:164:in `block in activate'
web_1                    | Exiting
web_1                    | Not notifying due to notify_release_stages :["production"]
web_1                    | /usr/local/bundle/gems/debug-1.5.0/lib/debug/server_dap.rb:158:in `send': undefined method `write' for nil:NilClass (NoMethodError)
web_1                    |      from /usr/local/bundle/gems/debug-1.5.0/lib/debug/server_dap.rb:183:in `send_event'
web_1                    |      from /usr/local/bundle/gems/debug-1.5.0/lib/debug/server_dap.rb:392:in `event'
web_1                    |      from /usr/local/bundle/gems/debug-1.5.0/lib/debug/session.rb:238:in `process_event'
web_1                    |      from /usr/local/bundle/gems/debug-1.5.0/lib/debug/session.rb:194:in `session_server_main'
web_1                    |      from /usr/local/bundle/gems/debug-1.5.0/lib/debug/session.rb:164:in `block in activate'
web_1 exited with code 1
```

**Comment by BobbyMcWho** [comment]
Seems like `@sock` was nil [here](https://github.com/ruby/debug/blob/master/lib/debug/server_dap.rb#L165) maybe?

**Comment by ko1** [comment]
Thank you I confirmed without foreman.

1. rails new app
2. `Add a require 'debug/open_nonstop' in the bin/rails file at the top of the file.`
3. `bin/rails server -p 3000 -b 0.0.0.0`
4. `rdbg -a`
5. `quit` command


```
$ bin/rails server -p 3000 -b 0.0.0.0
DEBUGGER: Debugger can attach via UNIX domain socket (/tmp/ruby-debug-sock-1000/ruby-debug-ko1-9092)
=> Booting Puma
=> Rails 7.0.3 application starting in development
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.6.4 (ruby 3.1.2-p20) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 9092
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
DEBUGGER: Connected.
unsupported:

$?:1
```

```
$ rdbg -a
# No sourcefile available for /home/ko1/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/single.rb
=>#0    [C] Thread#join at ~/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/single.rb:61
  #1    Puma::Single#run at ~/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.4/lib/puma/single.rb:61
  # and 16 frames (use `bt' command for all frames)

Stop by SIGURG
(rdbg:remote) quit    # command
Really quit? [Y/n]
disconnected (quit)
```
