### ISSUE TITLE
^c explodes terminal, requires `reset`

### ISSUE THREAD

**Issue by zenspider** [ruby/debug#651]
**Your environment**

* `ruby -v`: 3.1.x
* `rdbg -v`: 1.5.0

**Describe the bug**

This MIGHT be related to #603, but I'm not using foreman

In SOME contexts (still isolating), ^c in debug will totally explode. Newlines don't start new lines, all output from then on is garbled.

It does NOT reproduce with `rdbg -- -e 0`... so there's some extra context needed that I'm trying to isolate. Right now I'm dropping into debug via `binding.b` in a unit test... I'll add more as I figure it out.

**To Reproduce**

^c at prompt in debugger

**Expected behavior**

Either ignore the interrupt or exit cleanly.

**Comment by zenspider** [comment]
Apparently, rake needs to wrap the test run... I can't get a reproduction with just `ruby` invocations, even with full minitest runs. But with rake (using Minitest::TestTask or Rake's Rake::TestTask), it's a cinch.

```ruby
require "minitest/autorun"

describe 42 do
  it do
require "debug"
binding.b
    assert_equal 1, 2
  end
end
```

```ruby
require "rake/testtask"

Rake::TestTask.new :test do |t|
  t.test_files = FileList['./bug651.rb']
end
```

**Comment by ko1** [comment]
Thank you. I can confirm.
Now I can't find out the difference. Hmm.

**Comment by ko1** [comment]
Ah I understand.

1. `C-c` is send to rake process and ruby (test) process.
2. rake process terminates and STDIN/OUT/ERR will be closed
3. and something wrong.

```ruby
# Rakefile
task :foo do
  ruby "bug651.rb"
end
```
```ruby
# bug651.rb
p 1
binding.irb
p 2
binding.irb
```

```
[master]$ rake  foo
/home/ko1/.rbenv/versions/3.1.2/bin/ruby bug651.rb
1

From: bug651.rb @ line 3 :

    1:
    2: p 1
 => 3: binding.irb
    4: p 2
    5: binding.irb
    6:
    7: __END__

irb(main):001:0>
^C
rake aborted!
Interrupt:
/mnt/c/ko1/src/rb/ruby-debug/tmp/651/rakefile:2:in `block in <top (required)>'
Tasks: TOP => foo
(See full trace by running task with --trace)
irb(main):001:0>
2

From: bug651.rb @ line 5 :

    1:
    2: p 1
    3: binding.irb
    4: p 2
 => 5: binding.irb
    6:
    7: __END__

/home/ko1/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline/ansi.rb:248:in `raw': Input/output error (Errno::EIO)
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline/ansi.rb:248:in `cursor_pos'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline/line_editor.rb:150:in `reset'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline.rb:292:in `inner_readline'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/reline-0.3.1/lib/reline.rb:254:in `readmultiline'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/forwardable.rb:238:in `readmultiline'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/forwardable.rb:238:in `readmultiline'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb/input-method.rb:417:in `gets'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb.rb:539:in `block (2 levels) in eval_input'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb.rb:770:in `signal_status'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb.rb:538:in `block in eval_input'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb/ruby-lex.rb:284:in `lex'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb/ruby-lex.rb:253:in `block (2 levels) in each_top_level_statement'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb/ruby-lex.rb:250:in `loop'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb/ruby-lex.rb:250:in `block in each_top_level_statement'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb/ruby-lex.rb:249:in `catch'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb/ruby-lex.rb:249:in `each_top_level_statement'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb.rb:557:in `eval_input'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb.rb:491:in `block in run'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb.rb:490:in `catch'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb.rb:490:in `run'
        from /home/ko1/.rbenv/versions/3.1.2/lib/ruby/3.1.0/irb.rb:976:in `irb'
        from bug651.rb:5:in `<main>'

$?:1
```

With `pry` too.

```
[master]$ rake  foo
/home/ko1/.rbenv/versions/3.1.2/bin/ruby bug651.rb
1

From: /mnt/c/ko1/src/rb/ruby-debug/tmp/651/bug651.rb:4 :

    1: require 'pry'
    2:
    3: p 1
 => 4: binding.pry
    5: p 2
    6: binding.pry
    7:
    8: __END__
    9:

[1] pry(main)>
rake aborted!
Interrupt:
/mnt/c/ko1/src/rb/ruby-debug/tmp/651/rakefile:2:in `block in <top (required)>'
Tasks: TOP => foo
(See full trace by running task with --trace)
[1] pry(main)>
$?:1
```

I understand it is inconvenient. Can we solve it?

**Comment by zenspider** [comment]
I've never experienced this in the wild with pry... maybe they're handling signals in a different way?

**Comment by ko1** [comment]
On C-c, OS sends SIGINT to [foreground process group](https://en.wikipedia.org/wiki/Process_group). So it can be solved by set the group correctly. I'm not sure it is debugger's duty or not.

If anyone has knowledge about it, please reopen or make PR.
