### ISSUE TITLE
undefined method `unix_domain_socket_basedir' for DEBUGGER__:Module (NoMethodError)

### ISSUE THREAD

**Issue by ono-max** [ruby/debug#77]
```shell
$ exe/rdbg -A foo
/Users/naotto/workspace/debug/lib/debug/client.rb:68:in `connect_unix': undefined method `unix_domain_socket_basedir' for DEBUGGER__:Module (NoMethodError)
Did you mean?  unix_domain_socket_dir
	from /Users/naotto/workspace/debug/lib/debug/client.rb:37:in `initialize'
	from /Users/naotto/workspace/debug/lib/debug/client.rb:152:in `new'
	from /Users/naotto/workspace/debug/lib/debug/client.rb:152:in `connect'
	from exe/rdbg:31:in `<main>'

**Comment by olleolleolle** [comment]
Ah, fixed by #78.
