### ISSUE TITLE
When I enter `exit` during debug, error occurs and can't control process

### ISSUE THREAD

**Issue by ericgpks** [ruby/debug#873]
**Your environment**

* `ruby -v`:  3.1.1
* `rdbg -v`: 1.7.0

**Describe the bug**

When I enter `exit` during debug, I can't control the process anymore with some errors.
After that, I have to kill the process to restore the server.
```
    3| class IdeasController < ApplicationController
     4|   before_action :set_idea, only: %i[ show edit update destroy ]
     5| 
     6|   # GET /ideas or /ideas.json
     7|   def index
=>   8|     binding.break
     9|     @ideas = Idea.all
    10|   end
    11| 
    12|   # GET /ideas/1 or /ideas/1.json
=>#0    IdeasController#index at ~/Documents/GitHub/debug_test/app/controllers/ideas_controller.rb:8
  #1    ActionController::BasicImplicitRender#send_action(method="index", args=[]) at ~/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/basic_implicit_render.rb:6
  # and 75 frames (use `bt' command for all frames)
(rdbg) 

```
```
(rdbg) exit
Completed 500 Internal Server Error in 292001ms (ActiveRecord: 0.0ms | Allocations: 156753)


  
SystemExit (exit):
  
(rdbg)//Users/erisugi/Documents/GitHub/debug_test/app/controllers/ideas_controller.rb:1:in `exit'
(rdbg)//Users/erisugi/Documents/GitHub/debug_test/app/controllers/ideas_controller.rb:1:in `index'
app/controllers/ideas_controller.rb:8:in `index'
```

**To Reproduce**
1. Put break point with `binding.break` .
2. After stopping at break point, enter `exit`
3. Then some errors occur and can't control anymore (it is impossible to stop the server with ctrl + c).

**Expected behavior**

It is expected to behave like this when I enter `continue` or occur nothing.

**Additional context**

**Comment by ericgpks** [comment]
I'm sorry that I'm not good at writing English. If there is any unclear points, please contact me anytime.

**Comment by ko1** [comment]
Thank you for your report but I couldn't repro on my environment. Can you make reproducible steps with the small code?

**Comment by ericgpks** [comment]
Can I share my repository to repro the issue? 
https://github.com/ericgpks/debug_tests

**Comment by ericgpks** [comment]
I add more information to reproduction this.
1. make new rails app like this `rails new debug_test`
2. make scaffold in this app `rails generate scaffold idea name:string description:text picture:string`
3. add debug gem in Gemfile
4. write `binding.break` in index method in `app/controllers/ideas_controller.rb` 
5. run rails server
6. open the page `localhost:3000/ideas`
7. debugger will stop
8. enter exit and push enter button then it doesn't work anymore

My environment is macOS Ventura13.12.1 with Apple M1 Pro.

**Comment by ko1** [comment]
Thank you I repro the problem with the https://github.com/ruby/debug/issues/873#issuecomment-1460019714 steps.

(1) `exit` is evaluated as Ruby's `exit` method.
(2) If you want to quit the program, `quit` command or `kill` command are there.

----

> It is expected to behave like this when I enter continue or occur nothing.

Please use `continue` or `C-d`.

----

My survey:

Instead of `binding.break`, I wrote `exit` in `index` method, the output log is here:

```
$ bin/rails s
=> Booting Puma
=> Rails 7.0.4.3 application starting in development
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.6.5 (ruby 3.1.0-p0) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 27393
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
Started GET "/ideas" for ::1 at 2023-03-26 02:59:34 +0900
  ActiveRecord::SchemaMigration Pluck (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by IdeasController#index as HTML
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms | Allocations: 1568)



SystemExit (exit):

app/controllers/ideas_controller.rb:6:in `exit'
app/controllers/ideas_controller.rb:6:in `index'


^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2023-03-26 02:59:40 +0900 ===
- Goodbye!
Exiting
```

and it accepts `C-c` to terminate process.

With `debugger` method:

```
$ bin/rails s
=> Booting Puma
=> Rails 7.0.4.3 application starting in development
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.6.5 (ruby 3.1.0-p0) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 27440
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
Started GET "/ideas" for ::1 at 2023-03-26 03:00:49 +0900
  ActiveRecord::SchemaMigration Pluck (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by IdeasController#index as HTML
[1, 10] in ~/ruby/debug/tmp/debug_test/app/controllers/ideas_controller.rb
     1| class IdeasController < ApplicationController
     2|   before_action :set_idea, only: %i[ show edit update destroy ]
     3|
     4|   # GET /ideas or /ideas.json
     5|   def index
=>   6|     debugger
     7|     @ideas = Idea.all
     8|   end
     9|
    10|   # GET /ideas/1 or /ideas/1.json
=>#0    IdeasController#index at ~/ruby/debug/tmp/debug_test/app/controllers/ideas_controller.rb:6
  #1    ActionController::BasicImplicitRender#send_action(method="index", args=[]) at ~/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-7.0.4.3/lib/action_controller/metal/basic_implicit_render.rb:6
  # and 75 frames (use `bt' command for all frames)
(rdbg) exit
Completed 500 Internal Server Error in 3544ms (ActiveRecord: 0.0ms | Allocations: 103791)



SystemExit (exit):

(rdbg)//home/ko1/ruby/debug/tmp/debug_test/app/controllers/ideas_controller.rb:1:in `exit'
(rdbg)//home/ko1/ruby/debug/tmp/debug_test/app/controllers/ideas_controller.rb:1:in `index'
app/controllers/ideas_controller.rb:6:in `index'


^C^C^C
```

It doesn't accept `C-c` to terminate the process. It is a problem.

**Comment by gustavothecoder** [comment]
Looks like this problem is somehow solved in the [v1.7.2](https://github.com/ruby/debug/releases/tag/v1.7.2) release, so maybe  the solution is just to update to a newer version.

**Comment by ericgpks** [comment]
I checked with v1.9.1.

> (1) exit is evaluated as Ruby's exit method.
(2) If you want to quit the program, quit command (C-d) or kill command are there.

I see. I will do that.

> Please use continue (c in short).
OK. I will use `continue`.

Thank you so much!

**Comment by SampsonCrowley** [comment]
@ko1 is there any chance of _not_ evaluating exit as ruby exit? this is an extremely hard habit to break for anyone who has spent a lot of time on _any_ other debugging tool like IRB or Pry

exit should mean exit the debugger, just like all other ruby debuggers. it will be much easier for users to transition, and I really don't see any reason why anyone would want exit to mean exit program instead of exit debugger. to kill the program there's a command already for that via quit and kill
