### ISSUE TITLE
Debugger does not stop at an expected place in multi thread program

### ISSUE THREAD

**Issue by ono-max** [ruby/debug#929]
**Your environment**

* `ruby -v`: 
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin21]
* `rdbg -v`:
rdbg 1.7.1

**Describe the bug**
```shell
$ exe/rdbg f.rb
[1, 6] in f.rb
=>   1| def foo
     2|   Thread.new { sleep 5 }
     3| end
     4| 5.times do
     5|   foo
     6| end
=>#0    <main> at f.rb:1
(rdbg) b 2    # break command
#0  BP - Line  /Users/s15236/workspace/debug/f.rb:2 (line)
(rdbg) c    # continue command

$ # it doesn't stop.
```

**To Reproduce**

```ruby
def foo
  Thread.new { sleep 5 }
end
5.times do
  foo
end
```
1. Set a breakpoint at line 2.
2. Then continue.

**Expected behavior**
It should stop at line 2.

**Comment by ko1** [comment]
main thread terminates without waiting other threads (more exactly, at the end of main thread, ruby interpreter kills all living threads). So you need to wait at the end of the main thread.

```
$ exe/rdbg target.rb
[1, 10] in target.rb
=>   1| def foo
     2|   Thread.new { sleep 5 }
     3| end
     4| 5.times do
     5|   foo
     6| end
     7|
     8| sleep
     9|
    10| __END__
=>#0    <main> at target.rb:1
(rdbg) b 2    # break command
#0  BP - Line  /home/ko1/ruby/debug/target.rb:2 (line)
(rdbg) c    # continue command
[1, 10] in target.rb
     1| def foo
=>   2|   Thread.new { sleep 5 }
     3| end
     4| 5.times do
     5|   foo
     6| end
     7|
     8| sleep
     9|
    10| __END__
=>#0    block in foo at target.rb:2

Stop by #0  BP - Line  /home/ko1/ruby/debug/target.rb:2 (line)
(rdbg) info thread    # command
    #0 (sleep)@target.rb:1:in `<main>' (not under control)
    #1 (sleep)@target.rb:2:in `block in foo'
--> #2 (sleep)@target.rb:2:in `block in foo'
    #3 (sleep)@target.rb:2:in `block in foo'
    #4 (sleep)@target.rb:2:in `block in foo'
    #5 (sleep)@target.rb:2:in `block in foo'
```
