### ISSUE TITLE
"Only session_server can create thread_client"

### ISSUE THREAD

**Issue by jjb** [ruby/debug#932]
**Your environment**

➔ ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
➔ rdbg -v
rdbg 1.7.1
➔ bundle -v
Bundler version 2.4.8

**Describe the bug**

I just got the below error in my CI

There's exactly [1 hit on google](https://www.google.com/search?q="Only+session_server+can+create+thread_client"&client=opera&hs=rpk&ei=p1MWZKKdF5ioptQP-cGk0AQ&ved=0ahUKEwjijNPv2ub9AhUYlIkEHfkgCUoQ4dUDCA8&uact=5&oq="Only+session_server+can+create+thread_client"&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCAAQogRKBAhBGAFQjAdYxhNglhZoAXAAeACAAVyIAeUCkgEBNZgBAKABAcABAQ&sclient=gws-wiz-serp), a third-party site showing the source code: https://github.com/ruby/debug/blob/64552e2013338f6af03031dceed44494a1591eb1/lib/debug/session.rb#L1627

I have many many other successful runs, so I think this happens from some sort of very rare race condition. I don't know anything about what's going on, but I figured this is maybe a unique bug worth reporting, maybe caused by recent versions of other code.

Let me know if I can provide any more info!

```
bundle exec rails db:schema:load
#<Thread:0x00007fd154d2a1b8@DEBUGGER__::SESSION@server /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/debug-1.7.1/lib/debug/session.rb:177 run> terminated with exception (report_on_exception is true):
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/debug-1.7.1/lib/debug/session.rb:1611:in `create_thread_client': Only session_server can create thread_client (RuntimeError)
	from /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/debug-1.7.1/lib/debug/session.rb:1596:in `block in setup_threads'
	from /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/debug-1.7.1/lib/debug/session.rb:1592:in `each'
	from /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/debug-1.7.1/lib/debug/session.rb:1592:in `setup_threads'
	from /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/debug-1.7.1/lib/debug/session.rb:182:in `block in activate'
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/runtime.rb:63:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'debug'.
Gem Load Error is: Only session_server can create thread_client
Backtrace for gem load error is:
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/debug-1.7.1/lib/debug/session.rb:1611:in `create_thread_client'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/debug-1.7.1/lib/debug/session.rb:1596:in `block in setup_threads'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/debug-1.7.1/lib/debug/session.rb:1592:in `each'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/debug-1.7.1/lib/debug/session.rb:1592:in `setup_threads'
/home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/debug-1.7.1/lib/debug/session.rb:182:in `block in activate'
Bundler Error Backtrace:
 (Bundler::GemRequireError)
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/runtime.rb:59:in `block (2 levels) in require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/runtime.rb:55:in `each'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/runtime.rb:55:in `block in require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/runtime.rb:44:in `each'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.4.8/lib/bundler/runtime.rb:44:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.4.8/lib/bundler.rb:195:in `require'
	from /home/circleci/repo/config/application.rb:23:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/spring-4.1.1/lib/spring/application.rb:92:in `preload'
	from /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/spring-4.1.1/lib/spring/application.rb:166:in `serve'
	from /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/spring-4.1.1/lib/spring/application.rb:148:in `block in run'
	from /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/spring-4.1.1/lib/spring/application.rb:142:in `loop'
	from /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/spring-4.1.1/lib/spring/application.rb:142:in `run'
	from /home/circleci/repo/vendor/bundle/ruby/3.1.0/gems/spring-4.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
	from -e:1:in `<main>'

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by ko1** [comment]
could you try on current master?
5b29bd785b31048c9c2032ed997d1cb6ae3ac73a can solve this issue.

**Comment by ko1** [comment]
(or wait next 1.7.2 release (soon))

**Comment by jjb** [comment]
thanks, will updated to 1.7.2 and let you know if it recurs
